class Autogenerated {
  String? message;
  List<ValidationErr>? validationErr;

  Autogenerated({this.message, this.validationErr});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    if (json['validationErr'] != null) {
      validationErr = <ValidationErr>[];
      json['validationErr'].forEach((v) {
        validationErr!.add(ValidationErr.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['message'] = message;
    if (validationErr != null) {
      data['validationErr'] =
          validationErr!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ValidationErr {
  ValidationErr();

  ValidationErr.fromJson(Map<String, dynamic> json) {}

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    return data;
  }
}
